<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>10</LangVersion>
    <RootNamespace>HBTCombat.Tests</RootNamespace>
    <AssemblyName>HBTCombat.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HBTCombat\HBTCombat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BattlegroundDB">
      <HintPath>..\Lib\BattlegroundDB.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
