<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <UseWPF>true</UseWPF>
    <LangVersion>10</LangVersion>
    <RootNamespace>Hearthstone_Deck_Tracker</RootNamespace>
    <AssemblyName>HearthstoneDeckTracker</AssemblyName>
    <Version>1.52.14.7315</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

</Project>
